import type { DiscoverScenarioId } from '@/domain/scenarioCapabilities';

export type ArchitectureDocKind = 'design' | 'exec';

/** 能力层 · 架构 / AI 执行方案（md） */
export interface ScenarioArchitectureDoc {
  id: string;
  title: string;
  kind: ArchitectureDocKind;
  /** Markdown 正文 */
  markdown: string;
}

export const ARCHITECTURE_DOC_KIND_LABELS: Record<ArchitectureDocKind, string> = {
  design: '架构设计',
  exec: 'AI 执行方案',
};

function doc(
  scenarioId: string,
  kind: ArchitectureDocKind,
  title: string,
  markdown: string,
): ScenarioArchitectureDoc {
  return {
    id: `${scenarioId}-${kind}`,
    title,
    kind,
    markdown,
  };
}

/** 九大场景架构文件：对齐原型 Agent / Skill / Tool 真实 ID 与命令 */
export const SCENARIO_ARCHITECTURE_BY_ID: Record<
  DiscoverScenarioId,
  ScenarioArchitectureDoc[]
> = {
  'price-offer-monitor': [
    doc(
      'price-offer-monitor',
      'design',
      '价监 Offer · 架构设计',
      [
        '# 价监 Offer · 架构设计',
        '',
        '## 业务目标',
        '多渠道商城价格与 offer 异动监测，缩短调价闭环（样板：拉美 18 国）。',
        '',
        '## 能力映射（原型已挂载）',
        '| 层 | ID | 说明 |',
        '| --- | --- | --- |',
        '| Agent | `agent-price-monitor` | 价格监测专家 |',
        '| Skill | `skill-price-monitor` `/价格监测` | 异动清单 + 调价建议 |',
        '| Tool | `tool-market-intel` | 内部 Market Intel 采集连接器 |',
        '| Tool | `tool-ext-latam-price` | 拉美价盘哨兵（外部看板） |',
        '| 知识 | `kb-offer-monitor` | offer 监测口径 |',
        '',
        '## 数据流',
        '```',
        '商城价盘 → Market Intel / 价盘哨兵 → /价格监测 → Owner 确认调价',
        '```',
        '',
        '## 边界',
        '- 不下发自动改价，只产出建议与周报。',
        '- 区域外部工具默认 org 可见；金牌案例演示已放开 public。',
        '',
      ].join('\n'),
    ),
    doc(
      'price-offer-monitor',
      'exec',
      '价监 Offer · AI 执行方案',
      [
        '# 价监 Offer · AI 执行方案',
        '',
        '## 推荐入口',
        '金牌案例 `portal-case-latam-price` → 「一键打样」或「按此案例打样」。',
        '',
        '## 执行步骤',
        '1. 调用 `/价格监测`（PriceOfferMonitor）',
        '2. 确认监测国家/渠道白名单',
        '3. 导出异动表 + 调价建议，同步 GTM/渠道 Owner',
        '',
        '## 验收',
        '- 异动闭环时长可度量（样板：2 天 → 4 小时）',
        '- 周报可导出并带证据链截图（价盘哨兵）',
        '',
      ].join('\n'),
    ),
  ],
  'ecommerce-review': [
    doc(
      'ecommerce-review',
      'design',
      '电渠评论 · 架构设计',
      [
        '# 电渠评论 · 三段式架构',
        '',
        '## 链路（专家团多步接力）',
        '| 步 | Agent | Skill | 命令 |',
        '| --- | --- | --- | --- |',
        '| 1 | `agent-review-collect` | `skill-review-collect` | `/评论采集` |',
        '| 2 | `agent-review-translate` | `skill-review-translate` | `/评论翻译` |',
        '| 3 | `agent-review` | `skill-review-cluster` | `/评论分析` |',
        '',
        '## 外部工具',
        '- `tool-ext-apac-review` 亚太评论雷达（看板对照）',
        '',
        '## 交付物',
        '差评周报、主题聚类、行动建议（金牌：`portal-case-apac-voc`）。',
        '',
      ].join('\n'),
    ),
    doc(
      'ecommerce-review',
      'exec',
      '电渠评论 · AI 执行方案',
      [
        '# 电渠评论 · AI 执行方案',
        '',
        '## 打样',
        '场景顶栏选择「一键打样 · 多步接力」，同任务会话顺序执行三步。',
        '',
        '## 约束',
        '- 翻译步骤必须保留原文',
        '- 分析步骤依赖前序输出摘要（专家团会自动带上）',
        '',
        '## 单点调试',
        '也可打开金牌案例后只跑 `/评论分析`（不推荐跳过采集/翻译）。',
        '',
      ].join('\n'),
    ),
  ],
  'l10n-translation': [
    doc(
      'l10n-translation',
      'design',
      '小语种本地化 · 架构设计',
      [
        '# 小语种本地化 · 架构设计',
        '',
        '> 演示期复用评论链路的语种翻译能力做**物料初译**，非独立 L10n 引擎。',
        '',
        '## 能力映射',
        '| 层 | ID | 说明 |',
        '| --- | --- | --- |',
        '| Agent | `agent-review-translate` | 语种翻译专家 |',
        '| Skill | `skill-review-translate` `/评论翻译` | 多语→中英对照，保留原文 |',
        '',
        '## 配套思想层',
        '- 方案：`portal-playbook-l10n-pack`',
        '- 金牌案例：`portal-case-l10n-sku`（MEA 卖点卡）',
        '- 洞察：`portal-news-l10n-glossary`（术语表治理）',
        '',
        '## 边界',
        '- 终译/母语润色仍由本地化 Owner 人工；AI 负责初译与抽检加速。',
        '',
      ].join('\n'),
    ),
    doc(
      'l10n-translation',
      'exec',
      '小语种本地化 · AI 执行方案',
      [
        '# 小语种本地化 · AI 执行方案',
        '',
        '1. 阅读方案 PPT，对齐禁译表',
        '2. 打开金牌案例 → 调用 `/评论翻译`',
        '3. 指定目标语（英+中）、上传卖点卡源语表',
        '4. 导出对照稿交 Owner 终审',
        '',
        '## Prompt 提示',
        '在任务中注明「物料本地化模式」，避免模型按「电商评论」口吻输出。',
        '',
      ].join('\n'),
    ),
  ],
  'retail-training': [
    doc(
      'retail-training',
      'design',
      '门店陪练 · 架构设计',
      [
        '# 门店陪练 · 架构设计',
        '',
        '## 能力映射',
        '| 层 | ID | 命令 |',
        '| --- | --- | --- |',
        '| Agent | `agent-retail-coach` | 零售陪练专家 |',
        '| Skill | `skill-retail-coach` | `/陪练` |',
        '| Skill | `skill-training-gen` | `/培训内容`（脚本包生成） |',
        '| 连接器 | LMS（Skill connector） | 考核结果回写 |',
        '',
        '## 思想层',
        '- 金牌：`portal-case-retail-coach-gold`',
        '- 方案：`portal-playbook-retail-coach`',
        '- 培训：`portal-train-nova-coach`',
        '',
        '> 零售洞察 π（DOS/转化）属经营分析旁路，不计入本场景主链路。',
        '',
      ].join('\n'),
    ),
    doc(
      'retail-training',
      'exec',
      '门店陪练 · AI 执行方案',
      [
        '# 门店陪练 · AI 执行方案',
        '',
        '1. （可选）`/培训内容` 生成 Nova 话术包',
        '2. 打开金牌案例 → `/陪练`',
        '3. 选择 SKU 完成演练，查看考核分',
        '4. 同步 LMS / 店长看板',
        '',
      ].join('\n'),
    ),
  ],
  'customer-service': [
    doc(
      'customer-service',
      'design',
      '客诉服务 · 架构设计',
      [
        '# 客诉服务 · 架构设计',
        '',
        '## 能力映射',
        '| 层 | ID | 命令 |',
        '| --- | --- | --- |',
        '| Agent | `agent-knowledge` | 知识/话术专家 |',
        '| Skill | `skill-complaint-sop` | `/客诉` |',
        '| Skill | `skill-rag` | `/检索`（Milvus 分区） |',
        '| 连接器 | CSC Ticket（Skill connector） | 工单字段 |',
        '| 知识 | `kb-sop-complaint` | 电池过热等 SOP |',
        '',
        '## 思想层',
        '- 金牌：`portal-case-service-battery`',
        '- 方案：`portal-case-service-sop`（playbook）',
        '- 培训：`portal-train-rag-service`',
        '',
      ].join('\n'),
    ),
    doc(
      'customer-service',
      'exec',
      '客诉服务 · AI 执行方案',
      [
        '# 客诉服务 · AI 执行方案',
        '',
        '## 推荐打样',
        '金牌案例「电池过热客诉 SOP」→ `/客诉`',
        '',
        '1. 输入场景关键词（如电池过热）',
        '2. 核对返回话术中的 SOP 引用',
        '3. 按升级路径回填 CSC 工单',
        '',
        '## 备选',
        '培训课走 `/检索` 做带引用问答练习（与金牌案例互补）。',
        '',
      ].join('\n'),
    ),
  ],
  'ops-analytics': [
    doc(
      'ops-analytics',
      'design',
      '经营分析 · 架构设计',
      [
        '# 经营分析 / SO 报表 · 架构设计',
        '',
        '## 能力映射',
        '| 层 | ID | 说明 |',
        '| --- | --- | --- |',
        '| Agent | `agent-data-analysis` | 数据分析专家 |',
        '| Skill | `skill-so-report` `/so报表` | 排名、环比、IoT 剔除 |',
        '| Skill | `skill-data-analysis` `/数据分析` | 多源归因 |',
        '',
        '## 思想层',
        '- 金牌：`portal-case-so-mea-gold`',
        '- 方案：`portal-case-channel-rebate`（返利稽核 playbook，同链路）',
        '- 洞察：`portal-news-mea-so`',
        '',
      ].join('\n'),
    ),
    doc(
      'ops-analytics',
      'exec',
      '经营分析 · AI 执行方案',
      [
        '# 经营分析 · AI 执行方案',
        '',
        '1. 确认经营取数账号与代表处权限',
        '2. 打开金牌案例 → `/so报表`',
        '3. 勾选 IoT 剔除规则，生成周清清单',
        '4. 需要归因时追加 `/数据分析`',
        '',
      ].join('\n'),
    ),
  ],
  'fulfillment-settlement': [
    doc(
      'fulfillment-settlement',
      'design',
      '综履结算 · 架构设计',
      [
        '# 综履结算核验 · 架构设计',
        '',
        '> 本场景已与「欧洲营销物料合规」解耦：不再用 `/合规筛查` 冒充结算。',
        '',
        '## 能力映射',
        '| 层 | ID | 命令 |',
        '| --- | --- | --- |',
        '| Agent | `agent-data-analysis` | 差异分析与 Owner 分配 |',
        '| Skill | `skill-doc-parser` `/解析文档` | 结算/验收单字段抽取 |',
        '| Skill | `skill-data-analysis` `/数据分析` | 应结对照与差异清单 |',
        '| Tool | `tool-doc-ai` | Doc AI 运行时 |',
        '',
        '## 思想层',
        '- 金牌：`portal-case-fulfillment-recon`',
        '- 方案：`portal-playbook-fulfillment`',
        '',
      ].join('\n'),
    ),
    doc(
      'fulfillment-settlement',
      'exec',
      '综履结算 · AI 执行方案',
      [
        '# 综履结算 · AI 执行方案',
        '',
        '1. 准备结算 PDF + 应结明细表',
        '2. 打开金牌案例 → `/解析文档` 抽字段',
        '3. 续跑 `/数据分析` 出差异项',
        '4. 导出清单分配 Owner 并归档',
        '',
        '## 注意',
        '营销物料医疗用语抽检请走质量运营/合规案例（`portal-case-eu-compliance`），勿与本场景混用。',
        '',
      ].join('\n'),
    ),
  ],
  'knowledge-deposit': [
    doc(
      'knowledge-deposit',
      'design',
      '知识沉淀 · 架构设计',
      [
        '# 组织知识沉淀 · 架构设计',
        '',
        '## 能力映射',
        '| 层 | ID | 命令 |',
        '| --- | --- | --- |',
        '| Agent | `agent-file-organize` | 入库整理 |',
        '| Agent | `agent-knowledge` | 问答验收 |',
        '| Skill | `skill-file-archive` `/文件整理` | 智能归档 |',
        '| Skill | `skill-rag` `/检索` | Milvus 分区检索 |',
        '| Skill | `skill-rerank` `/rerank` | 命中重排 |',
        '',
        '## 思想层',
        '- 金牌：`portal-case-knowledge-archive`',
        '- 方案：`portal-playbook-knowledge`',
        '- 培训：`portal-train-knowledge-rag`',
        '',
        '> 服务条线客诉 RAG 培训（`portal-train-rag-service`）归客诉场景，不再双挂。',
        '',
      ].join('\n'),
    ),
    doc(
      'knowledge-deposit',
      'exec',
      '知识沉淀 · AI 执行方案',
      [
        '# 知识沉淀 · AI 执行方案',
        '',
        '1. 打开金牌案例 → `/文件整理` 完成入库切片',
        '2. `/检索` 按部门分区提问并核对引用',
        '3. 低质量命中时跑 `/rerank` 或修正切片标签',
        '4. 对照培训课完成管理员验收清单',
        '',
      ].join('\n'),
    ),
  ],
  'hr-interview': [
    doc(
      'hr-interview',
      'design',
      '招聘速评 · 架构设计',
      [
        '# 招聘人岗速评 · 架构设计',
        '',
        '## 能力映射',
        '| 层 | ID | 命令 |',
        '| --- | --- | --- |',
        '| Agent | `agent-hr-resume` | HR 协同专家（编排三技能） |',
        '| Skill | `skill-jd-parser` | `/jd解析` |',
        '| Skill | `skill-resume-screen` | `/简历筛选` |',
        '| Skill | `skill-interview-analysis` | `/面试分析` |',
        '| Tool | `tool-hr-hub` | HR Hub 连接器 |',
        '',
        '## 说明',
        '产品叙事里的「三 Agent」在原型中收敛为 **单 Agent + 三 Skill**，打样时按步骤切换命令即可。',
        '',
        '## 思想层',
        '- 金牌：`portal-case-hr-batch`',
        '- 培训：`portal-train-hr-resume`',
        '',
      ].join('\n'),
    ),
    doc(
      'hr-interview',
      'exec',
      '招聘速评 · AI 执行方案',
      [
        '# 招聘速评 · AI 执行方案',
        '',
        '1. 打开金牌案例（主 Skill：`/简历筛选`）',
        '2. 需要结构化 JD 时先跑 `/jd解析`',
        '3. 导入简历包，导出人岗匹配报告',
        '4. 面试后可选 `/面试分析` 生成评估',
        '',
      ].join('\n'),
    ),
  ],
};

export function getScenarioArchitectureDocs(scenarioId: string): ScenarioArchitectureDoc[] {
  if (scenarioId in SCENARIO_ARCHITECTURE_BY_ID) {
    return SCENARIO_ARCHITECTURE_BY_ID[scenarioId as DiscoverScenarioId];
  }
  return [];
}
