import type { PrototypeAgentSeed } from '@/domain/prototype/types';

/** 来源：index.html DEFAULT_AGENTS（Phase1 打样 14 Agent） */
export const PROTOTYPE_AGENTS: PrototypeAgentSeed[] = [
  { id: 'agent-data-analysis', name: '数据分析 Agent', desc: '【办公提效】多源数据自动分析，融合 ISRP/零售/电商数据输出洞察报表', category: 'office', bizLine: 'GTM/渠道', homeTag: 'gtm', author: '华为 MSS', published: true, invokes: 4280, skillIds: ['skill-data-analysis', 'skill-so-report', 'skill-work-summary'], chatId: 'marketing', icon: 'fa-chart-pie', color: 'from-zinc-700 to-zinc-900', systemPrompt: '你是 MSS 数据分析专家，优先使用多源数据分析与 SO 报表 Skill。' },
  { id: 'agent-doc-review', name: '文档解读 Agent', desc: '【办公提效】营销物料/合同/招投标文档内容正确性、风险与合规筛查', category: 'office', bizLine: 'MKT', homeTag: 'mkt', author: '华为 MSS', published: true, invokes: 3150, skillIds: ['skill-doc-compliance', 'skill-doc-gen', 'skill-doc-parser'], chatId: 'knowledge', icon: 'fa-file-shield', color: 'from-stone-500 to-zinc-700' },
  { id: 'agent-file-organize', name: '文件整理 Agent', desc: '【办公提效】本地文件夹/员工助手/Email 多源文件清洗归档与个人总结', category: 'office', bizLine: 'HR', homeTag: 'hr', author: '华为 MSS', published: true, invokes: 1890, skillIds: ['skill-file-archive', 'skill-work-summary', 'skill-doc-parser'], chatId: 'marketing', icon: 'fa-folder-tree', color: 'from-slate-600 to-slate-800' },
  { id: 'agent-ppt', name: 'PPT 生成 Agent', desc: '【办公提效】多源数据驱动 PPT 自动生成，支持员工助手内部 POC 验证', category: 'office', bizLine: 'MKT/GTM', homeTag: 'mkt', author: '华为 MSS', published: true, invokes: 2240, skillIds: ['skill-ppt-gen', 'skill-data-analysis', 'skill-doc-gen'], chatId: 'marketing', icon: 'fa-file-powerpoint', color: 'from-neutral-500 to-zinc-700' },
  { id: 'agent-meeting', name: '会议纪要 Agent', desc: '【办公提效】会议纪要 AI 自动生成，小批量试点 60% AI + 40% 人工', category: 'office', bizLine: 'HR', homeTag: 'hr', author: '华为 MSS', published: true, invokes: 5340, skillIds: ['skill-meeting-minutes', 'skill-doc-gen', 'skill-wecom'], chatId: 'marketing', icon: 'fa-clipboard-list', color: 'from-slate-500 to-zinc-700' },
  { id: 'agent-launch-sentiment', name: '舆情快报 Agent', desc: '【管理提效】产品发布舆情 AI 分析快报，面向 MKT/服务', category: 'manage', bizLine: 'MKT/服务', homeTag: 'mkt', author: '华为 MSS', published: true, invokes: 1420, skillIds: ['skill-launch-sentiment', 'skill-doc-gen', 'skill-wecom'], chatId: 'marketing', icon: 'fa-bullhorn', color: 'from-zinc-600 to-zinc-800' },
  { id: 'agent-survey', name: '问卷洞察 Agent', desc: '【管理提效】洞察部用户问卷调研设计与开放题洞察分析', category: 'manage', bizLine: 'MKT', homeTag: 'mkt', author: '华为 MSS', published: true, invokes: 980, skillIds: ['skill-survey-insight', 'skill-data-analysis', 'skill-doc-gen'], chatId: 'marketing', icon: 'fa-square-poll-vertical', color: 'from-stone-500 to-zinc-600' },
  { id: 'agent-review', name: '评论分析 Agent', desc: '【管理提效】Amazon/Lazada 订单评论多语种聚类分析，面向电商/服务/MKT', category: 'manage', bizLine: '电商/服务', homeTag: 'ecommerce', author: '华为 MSS', published: true, invokes: 2780, skillIds: ['skill-review-cluster', 'skill-data-analysis', 'skill-doc-gen'], chatId: 'knowledge', icon: 'fa-comments', color: 'from-slate-500 to-slate-700' },
  { id: 'agent-retail-insight', name: '零售洞察 Agent', desc: '【管理提效】零售信息洞察 π 例行报告，门店 DOS/转化/陈列分析', category: 'manage', bizLine: '零售/电商', homeTag: 'retail', author: '华为 MSS', published: true, invokes: 3680, skillIds: ['skill-retail-insight', 'skill-so-report', 'skill-doc-gen'], chatId: 'marketing', icon: 'fa-store', color: 'from-neutral-600 to-zinc-800' },
  { id: 'agent-price-monitor', name: '价格监测 Agent', desc: '【管理提效】18 国多渠道价格 & offer 监测，覆盖 5347 行/周级入表', category: 'manage', bizLine: '渠道/电商/GTM', homeTag: 'gtm', author: '华为 MSS', published: true, invokes: 4120, skillIds: ['skill-price-monitor', 'skill-data-analysis', 'skill-wecom'], chatId: 'marketing', icon: 'fa-tags', color: 'from-emerald-800 to-emerald-900' },
  { id: 'agent-hr-resume', name: '简历筛选 Agent', desc: '【流程提效】JD 解析 + 简历筛选 + 面试分析三 Agent 协同，面向 HR/用人部门', category: 'process', bizLine: 'HR', homeTag: 'hr', author: '华为 MSS', published: true, invokes: 1560, skillIds: ['skill-jd-parser', 'skill-resume-screen', 'skill-interview-analysis'], chatId: 'knowledge', icon: 'fa-user-check', color: 'from-stone-600 to-zinc-800' },
  { id: 'agent-training', name: '培训内容 Agent', desc: '【流程提效】Nova 新品培训内容生成，多 Agent 对抗协同与门店陪练衔接', category: 'process', bizLine: '零售/门店', homeTag: 'retail', author: '华为 MSS', published: true, invokes: 1890, skillIds: ['skill-training-gen', 'skill-retail-coach', 'skill-doc-gen'], chatId: 'knowledge', icon: 'fa-graduation-cap', color: 'from-slate-600 to-zinc-700' },
  { id: 'agent-knowledge', name: '知识 Agent', desc: '【体验提升】企业 RAG 问答，带引用的文献溯源与 SOP 检索', category: 'experience', bizLine: '服务', homeTag: 'service', author: '华为 MSS', published: true, invokes: 3520, skillIds: ['skill-rag', 'skill-rerank', 'skill-complaint-sop'], chatId: 'knowledge', icon: 'fa-book-open', color: 'from-zinc-600 to-zinc-800' },
  { id: 'agent-retail-coach', name: '零售陪练 Agent', desc: '【体验提升】门店 AI 陪练、卖点演练与考核反馈，衔接培训内容 Agent', category: 'experience', bizLine: '零售/门店', homeTag: 'retail', author: '华为 MSS', published: true, invokes: 860, skillIds: ['skill-retail-coach', 'skill-training-gen', 'skill-wecom'], chatId: 'knowledge', icon: 'fa-headset', color: 'from-zinc-700 to-zinc-900' },
];
