import type { AssetVisibility, DeptId, PortalAssetType, RegionId } from '@/domain/orgTaxonomy';

/** 门户知识地图内容（案例 / 洞察 / 培训 / 讯息） */
export interface PortalContentItem {
  id: string;
  type: Extract<PortalAssetType, 'case' | 'insight' | 'training' | 'news'>;
  title: string;
  desc: string;
  icon: string;
  ownerDeptIds?: DeptId[];
  ownerRegionId?: RegionId | null;
  publisher?: string;
  publisherUserId?: string;
  sourceType?: 'internal' | 'external';
  visibility?: AssetVisibility;
  homepageUrl?: string;
  /** 关联平台资产，点击时优先跳转 */
  kbDocId?: string;
  agentId?: string;
  skillId?: string;
  toolId?: string;
  publishedAt: string;
  scenarioTags?: string[];
  /** 运营上架；缺省 true */
  published?: boolean;
}

export const PORTAL_CONTENT_TYPE_LABELS: Record<PortalContentItem['type'], string> = {
  case: '案例',
  insight: '洞察',
  training: '培训赋能',
  news: '前沿洞察',
};

export const PROTOTYPE_PORTAL_CONTENT: PortalContentItem[] = [
  {
    id: 'portal-case-latam-price',
    type: 'case',
    title: '拉美价监 Agent 落地案例',
    desc: '拉美区用价格监测 Agent + 外部价盘哨兵，周级异动闭环从 2 天缩到 4 小时',
    icon: 'fa-lightbulb',
    ownerDeptIds: ['gtm', 'channel'],
    ownerRegionId: 'latam',
    publisher: 'Jacky',
    publisherUserId: 'm3',
    agentId: 'agent-price-monitor',
    toolId: 'tool-ext-latam-price',
    publishedAt: '2026-07-10',
    scenarioTags: ['价格监测', '区域自建'],
    visibility: 'org',
    kbDocId: 'kb-offer-monitor',
  },
  {
    id: 'portal-case-eu-compliance',
    type: 'case',
    title: '欧洲营销物料合规抽检',
    desc: '文档解读 Agent + EU Checklist 外部工具，医疗用语风险检出率提升 35%',
    icon: 'fa-shield-halved',
    ownerDeptIds: ['mkt', 'quality'],
    ownerRegionId: 'europe',
    publisher: 'Bruce',
    publisherUserId: 'm2',
    agentId: 'agent-doc-review',
    toolId: 'tool-ext-eu-compliance',
    kbDocId: 'kb-wearable-medical',
    publishedAt: '2026-07-08',
    scenarioTags: ['合规', '质量与运营'],
    visibility: 'org',
  },
  {
    id: 'portal-insight-q3-campaign',
    type: 'insight',
    title: 'Q3 全渠道活动 AI 洞察摘要',
    desc: 'MKT 洞察部整理：活动节奏、预算池与开放题问卷结论一页纸',
    icon: 'fa-chart-line',
    ownerDeptIds: ['mkt'],
    ownerRegionId: null,
    publisher: 'Sarah',
    publisherUserId: 'g1',
    kbDocId: 'kb-campaign-q3',
    skillId: 'skill-survey-insight',
    publishedAt: '2026-07-09',
    scenarioTags: ['活动', '问卷'],
  },
  {
    id: 'portal-insight-apac-review',
    type: 'insight',
    title: '亚太电商差评主题周报',
    desc: '评论分析 Agent 聚类结果 + 亚太评论雷达看板联动解读',
    icon: 'fa-comments',
    ownerDeptIds: ['ecommerce', 'service'],
    ownerRegionId: 'apac',
    agentId: 'agent-review',
    toolId: 'tool-ext-apac-review',
    publishedAt: '2026-07-11',
    scenarioTags: ['评论分析'],
  },
  {
    id: 'portal-train-nova-coach',
    type: 'training',
    title: 'Nova 门店陪练赋能课',
    desc: '零售培训：卖点脚本 → AI 陪练 → 考核反馈完整路径',
    icon: 'fa-graduation-cap',
    ownerDeptIds: ['retail'],
    ownerRegionId: 'apac',
    agentId: 'agent-retail-coach',
    skillId: 'skill-training-gen',
    kbDocId: 'kb-nova-training',
    publishedAt: '2026-07-07',
    scenarioTags: ['门店', '培训'],
  },
  {
    id: 'portal-train-hr-resume',
    type: 'training',
    title: 'HR 三 Agent 协同招聘工作坊',
    desc: 'JD 解析 → 简历筛选 → 面试分析，带示例任务包',
    icon: 'fa-user-check',
    ownerDeptIds: ['hr'],
    ownerRegionId: null,
    agentId: 'agent-hr-resume',
    skillId: 'skill-resume-screen',
    kbDocId: 'kb-jd-template',
    publishedAt: '2026-07-05',
    scenarioTags: ['招聘'],
  },
  {
    id: 'portal-news-ai-frontier',
    type: 'news',
    title: 'MSS AI 前沿：Agent 上架规范更新',
    desc: '机关与区域自建 Skill/外部工具登记字段、可见性与审核口径说明',
    icon: 'fa-newspaper',
    ownerDeptIds: ['quality'],
    ownerRegionId: null,
    publisher: 'MSS AI变革',
    kbDocId: 'kb-agent-playbook',
    publishedAt: '2026-07-12',
    scenarioTags: ['规范', '赋能'],
  },
  {
    id: 'portal-news-mea-so',
    type: 'news',
    title: '中东非 SO 周报自动化试点',
    desc: '数据分析 + SO 报表 Skill 组合，代表处周报模板开放试用',
    icon: 'fa-table',
    ownerDeptIds: ['gtm', 'channel'],
    ownerRegionId: 'mea',
    skillId: 'skill-so-report',
    agentId: 'agent-data-analysis',
    publishedAt: '2026-07-06',
    scenarioTags: ['SO', '代表处'],
  },
  {
    id: 'portal-case-service-sop',
    type: 'case',
    title: '客诉 SOP 知识 Agent 实践',
    desc: '服务条线用知识 Agent 检索电池过热 SOP，一线话术一致性提升',
    icon: 'fa-headset',
    ownerDeptIds: ['service'],
    ownerRegionId: 'eurasia',
    agentId: 'agent-knowledge',
    skillId: 'skill-complaint-sop',
    kbDocId: 'kb-sop-complaint',
    publishedAt: '2026-07-04',
    scenarioTags: ['客诉', 'SOP'],
  },
  {
    id: 'portal-insight-retail-pi',
    type: 'insight',
    title: '零售洞察 π · 门店转化解读',
    desc: 'DOS / 转化 / 陈列合规周报样例，适配拉美与欧亚门店',
    icon: 'fa-store',
    ownerDeptIds: ['retail'],
    ownerRegionId: 'latam',
    agentId: 'agent-retail-insight',
    kbDocId: 'kb-retail-pi',
    publishedAt: '2026-07-11',
    scenarioTags: ['零售', '洞察π'],
  },
  {
    id: 'portal-train-quality-audit',
    type: 'training',
    title: '质量运营审计与 Agent 抽检培训',
    desc: '文档合规抽检、调用审计与问题闭环流程赋能课',
    icon: 'fa-clipboard-check',
    ownerDeptIds: ['quality'],
    ownerRegionId: null,
    kbDocId: 'kb-quality-audit',
    skillId: 'skill-doc-compliance',
    publishedAt: '2026-07-03',
    scenarioTags: ['审计', '质量'],
  },
  {
    id: 'portal-news-ext-tools',
    type: 'news',
    title: '外部 AI 工具精选周刊',
    desc: '整理可登记到智枢的外部看板与采集工具，本周重点：价监 / 评论 / 合规',
    icon: 'fa-link',
    ownerDeptIds: ['gtm', 'ecommerce', 'quality'],
    ownerRegionId: null,
    sourceType: 'external',
    homepageUrl: 'https://example.com/mss-ai-tool-weekly',
    publishedAt: '2026-07-13',
    scenarioTags: ['外部工具', '赋能'],
  },
  {
    id: 'portal-case-channel-rebate',
    type: 'case',
    title: '渠道返利稽核 Agent 试点',
    desc: '渠道部用数据分析 + SO 报表组合，代表处返利异常周清',
    icon: 'fa-diagram-project',
    ownerDeptIds: ['channel', 'gtm'],
    ownerRegionId: 'mea',
    agentId: 'agent-data-analysis',
    skillId: 'skill-so-report',
    toolId: 'tool-ext-latam-price',
    kbDocId: 'kb-rebate-q3',
    publishedAt: '2026-07-02',
    scenarioTags: ['返利', '代表处'],
  },
  {
    id: 'portal-insight-russia-dos',
    type: 'insight',
    title: '欧亚门店 DOS 异动解读',
    desc: '零售洞察 Agent 输出库存与转化交叉解读样例',
    icon: 'fa-chart-pie',
    ownerDeptIds: ['retail'],
    ownerRegionId: 'eurasia',
    agentId: 'agent-retail-insight',
    publishedAt: '2026-07-01',
    scenarioTags: ['零售', '洞察π'],
  },
  {
    id: 'portal-train-ppt-office',
    type: 'training',
    title: '办公提效：PPT / 会议纪要速成',
    desc: 'MKT/GTM 共用：多源数据出 PPT + 会议纪要双 Skill 实操课',
    icon: 'fa-file-powerpoint',
    ownerDeptIds: ['mkt', 'gtm', 'hr'],
    ownerRegionId: null,
    agentId: 'agent-ppt',
    skillId: 'skill-meeting-minutes',
    publishedAt: '2026-06-28',
    scenarioTags: ['办公提效', 'PPT'],
  },
  {
    id: 'portal-news-latam-launch',
    type: 'news',
    title: '拉美上市节奏 AI 协同播报',
    desc: 'GTM 与质量运营联合：准入 Checklist + 价监周报上架说明',
    icon: 'fa-rocket',
    ownerDeptIds: ['gtm', 'quality'],
    ownerRegionId: 'latam',
    kbDocId: 'kb-latam-compliance',
    publishedAt: '2026-07-12',
    scenarioTags: ['上市', '准入'],
  },
  {
    id: 'portal-case-hr-batch',
    type: 'case',
    title: 'HR 批量简历筛选周案例',
    desc: '用人部门 + HR：三 Agent 协同处理 200+ 简历匹配报告',
    icon: 'fa-users',
    ownerDeptIds: ['hr'],
    ownerRegionId: 'apac',
    publisher: 'RD-Team',
    publisherUserId: 'r1',
    agentId: 'agent-hr-resume',
    skillId: 'skill-jd-parser',
    kbDocId: 'kb-resume-rubric',
    publishedAt: '2026-06-30',
    scenarioTags: ['招聘', 'HR'],
  },
  {
    id: 'portal-insight-sentiment',
    type: 'insight',
    title: '欧洲发布会舆情快报样例',
    desc: '舆情快报 Agent 输出主题聚类与风险信号一页纸',
    icon: 'fa-bullhorn',
    ownerDeptIds: ['mkt', 'service'],
    ownerRegionId: 'europe',
    publisher: 'Bruce',
    publisherUserId: 'm2',
    agentId: 'agent-launch-sentiment',
    publishedAt: '2026-07-09',
    scenarioTags: ['舆情', '发布会'],
  },
  {
    id: 'portal-train-rag-service',
    type: 'training',
    title: '服务条线 RAG 问答赋能',
    desc: '知识 Agent + 客诉 SOP：一线检索话术与引用规范',
    icon: 'fa-book-open',
    ownerDeptIds: ['service'],
    ownerRegionId: null,
    agentId: 'agent-knowledge',
    skillId: 'skill-complaint-sop',
    publishedAt: '2026-07-08',
    scenarioTags: ['客诉', 'SOP'],
  },
];
