import type { PrototypeToolSeed } from '@/domain/prototype/types';
import { buildExternalToolSeedsFromCatalog } from '@/domain/buildExternalToolSeeds';
import { EXTERNAL_TOOL_SHELF_EXCLUDE_IDS } from '@/domain/externalToolTaxonomy';
import { internalToolAssetUrl } from '@/domain/toolLogo';

/**
 * 已下线的演示连接器 / 区域假工具（不再进配置工具种子）。
 * 持久化缓存里若仍有这些 id，加载时剔除。
 */
export const RETIRED_DEMO_TOOL_IDS = [
  'tool-isrp',
  'tool-doc-ai',
  'tool-market-intel',
  'tool-hr-hub',
  'tool-wecom-api',
  'tool-ext-latam-price',
  'tool-ext-eu-compliance',
  'tool-ext-apac-review',
  'tool-ext-latam-private-playbook',
  ...EXTERNAL_TOOL_SHELF_EXCLUDE_IDS,
] as const;

/** 门户 Tool 种子：公司内部 AI（外部 SaaS 见 CSV catalog） */
const CORE_PROTOTYPE_TOOLS: PrototypeToolSeed[] = [
  // —— 业界常用 AI 工具架（场景导航默认展示；有 ai-saas 标签时由 catalog 覆盖）——
  {
    id: 'tool-saas-cursor',
    name: 'Cursor',
    desc: 'AI 原生代码编辑器，适合研发编码与 Agent 协作',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 98000,
    icon: 'fa-code',
    tags: ['ai-saas', '编码'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://cursor.com',
    scenarioTags: ['编码助手'],
  },
  {
    id: 'tool-saas-claude-code',
    name: 'Claude Code',
    desc: 'Anthropic 终端/IDE 编码助手，适合复杂工程改造',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 72000,
    icon: 'fa-terminal',
    tags: ['ai-saas', '编码'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://claude.ai/code',
    scenarioTags: ['编码助手'],
  },
  {
    id: 'tool-saas-gemini',
    name: 'Gemini',
    desc: 'Google 多模态助手，适合检索、创作与分析',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 120000,
    icon: 'fa-sparkles',
    tags: ['ai-saas', '对话'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://gemini.google.com',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-chatgpt',
    name: 'ChatGPT',
    desc: 'OpenAI 通用对话与生产力助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 210000,
    icon: 'fa-comments',
    tags: ['ai-saas', '对话'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://chatgpt.com',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-doubao',
    name: '豆包',
    desc: '字节跳动对话助手，适合中文办公与创作',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 88000,
    icon: 'fa-comment',
    tags: ['ai-saas', '对话'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.doubao.com',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-kimi',
    name: 'Kimi',
    desc: '月之暗面长上下文助手，适合研报与长文档',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 65000,
    icon: 'fa-book-open',
    tags: ['ai-saas', '研究'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://kimi.moonshot.cn',
    scenarioTags: ['长文研究'],
  },
  {
    id: 'tool-saas-workbuddy',
    name: 'WorkBuddy',
    desc: '腾讯云办公 AI Agent 工作台，适合任务拆解与多专家并行交付',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 45000,
    icon: 'fa-briefcase',
    tags: ['ai-saas', '办公', '协作'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.workbuddy.ai/',
    scenarioTags: ['企业协作'],
  },
  {
    id: 'tool-saas-copilot',
    name: 'GitHub Copilot',
    desc: 'GitHub AI 编码补全与对话助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 150000,
    icon: 'fa-code',
    tags: ['ai-saas', '编码'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://github.com/features/copilot',
    scenarioTags: ['编码助手'],
  },
  {
    id: 'tool-saas-perplexity',
    name: 'Perplexity',
    desc: 'AI 搜索与研究助手，适合调研与引用来源',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 92000,
    icon: 'fa-magnifying-glass',
    tags: ['ai-saas', '研究'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.perplexity.ai',
    scenarioTags: ['长文研究'],
  },
  {
    id: 'tool-saas-notion-ai',
    name: 'Notion AI',
    desc: 'Notion 内嵌写作与知识整理助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 78000,
    icon: 'fa-note-sticky',
    tags: ['ai-saas', '写作', '办公'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.notion.so/product/ai',
    scenarioTags: ['企业协作'],
  },
  {
    id: 'tool-saas-tongyi',
    name: '通义千问',
    desc: '阿里云通义对话与办公助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 110000,
    icon: 'fa-comments',
    tags: ['ai-saas', '对话'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://tongyi.aliyun.com',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-wenxin',
    name: '文心一言',
    desc: '百度文心大模型对话助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 95000,
    icon: 'fa-comment',
    tags: ['ai-saas', '对话'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://yiyan.baidu.com',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-midjourney',
    name: 'Midjourney',
    desc: 'AI 图像生成，适合创意与视觉物料',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 130000,
    icon: 'fa-image',
    tags: ['ai-saas', '生图'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.midjourney.com',
    scenarioTags: ['图像创作'],
  },
  {
    id: 'tool-saas-gamma',
    name: 'Gamma',
    desc: 'AI 演示文稿与落地页生成',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 54000,
    icon: 'fa-file-powerpoint',
    tags: ['ai-saas', '写作', '办公'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://gamma.app',
    scenarioTags: ['企业协作'],
  },
  {
    id: 'tool-saas-runway',
    name: 'Runway',
    desc: 'AI 视频生成与剪辑，适合创意短片与物料',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 48000,
    icon: 'fa-clapperboard',
    tags: ['ai-saas', '生视频'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://runwayml.com',
    scenarioTags: ['视频创作'],
  },
  {
    id: 'tool-saas-kling',
    name: '可灵',
    desc: '快手可灵 AI 视频生成',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 62000,
    icon: 'fa-video',
    tags: ['ai-saas', '生视频'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://klingai.com',
    scenarioTags: ['视频创作'],
  },
  {
    id: 'tool-saas-jimeng',
    name: '即梦',
    desc: '字节即梦 AI 生图与生视频',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 71000,
    icon: 'fa-wand-magic-sparkles',
    tags: ['ai-saas', '生视频', '生图'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://jimeng.jianying.com',
    scenarioTags: ['视频创作', '图像创作'],
  },
  {
    id: 'tool-saas-claude',
    name: 'Claude',
    desc: 'Anthropic 对话与长文推理助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 168000,
    icon: 'fa-comments',
    tags: ['ai-saas', '对话', '写作'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://claude.ai',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-deepseek',
    name: 'DeepSeek',
    desc: '深度求索对话与代码助手，性价比高',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 145000,
    icon: 'fa-brain',
    tags: ['ai-saas', '对话', '编码'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://chat.deepseek.com',
    scenarioTags: ['通用对话', '编码助手'],
  },
  {
    id: 'tool-saas-metaso',
    name: '秘塔AI搜索',
    desc: '国内 AI 搜索，适合无广告调研与资料汇总',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 58000,
    icon: 'fa-magnifying-glass',
    tags: ['ai-saas', '搜索'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://metaso.cn',
    scenarioTags: ['长文研究'],
  },
  {
    id: 'tool-saas-jasper',
    name: 'Jasper',
    desc: '营销文案与品牌写作助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 42000,
    icon: 'fa-pen',
    tags: ['ai-saas', '写作'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.jasper.ai',
    scenarioTags: ['企业协作'],
  },
  {
    id: 'tool-saas-windsurf',
    name: 'Windsurf',
    desc: 'Codeium AI IDE，适合 Agent 式编程',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 67000,
    icon: 'fa-code',
    tags: ['ai-saas', '编码'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://windsurf.com',
    scenarioTags: ['编码助手'],
  },
  {
    id: 'tool-saas-ideogram',
    name: 'Ideogram',
    desc: 'AI 生图，文字排版与设计物料表现强',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 56000,
    icon: 'fa-image',
    tags: ['ai-saas', '生图'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://ideogram.ai',
    scenarioTags: ['图像创作'],
  },
  {
    id: 'tool-saas-pika',
    name: 'Pika',
    desc: 'AI 短视频生成，适合创意短片',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 39000,
    icon: 'fa-film',
    tags: ['ai-saas', '生视频'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://pika.art',
    scenarioTags: ['视频创作'],
  },
  {
    id: 'tool-saas-luma',
    name: 'Luma Dream Machine',
    desc: 'Luma AI 视频生成，适合镜头感短片',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 41000,
    icon: 'fa-clapperboard',
    tags: ['ai-saas', '生视频'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://lumalabs.ai/dream-machine',
    scenarioTags: ['视频创作'],
  },
  {
    id: 'tool-saas-yuanbao',
    name: '腾讯元宝',
    desc: '腾讯混元对话与搜索助手，适合中文办公问答',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 88000,
    icon: 'fa-comments',
    tags: ['ai-saas', '对话', '搜索'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://yuanbao.tencent.com',
    scenarioTags: ['通用对话'],
  },
  {
    id: 'tool-saas-copyai',
    name: 'Copy.ai',
    desc: '营销文案与 GTM 内容生成助手',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 36000,
    icon: 'fa-pen-nib',
    tags: ['ai-saas', '写作'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.copy.ai',
    scenarioTags: ['企业协作'],
  },
  {
    id: 'tool-saas-ms-copilot',
    name: 'Microsoft Copilot',
    desc: 'Microsoft 365 办公助手，覆盖文档、表格与邮件',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 140000,
    icon: 'fa-briefcase',
    tags: ['ai-saas', '办公', '协作'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://copilot.microsoft.com',
    scenarioTags: ['办公提效', '企业协作'],
  },
  {
    id: 'tool-saas-feishu',
    name: '飞书智能伙伴',
    desc: '飞书办公 AI，支持纪要、文档与协作问答',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 72000,
    icon: 'fa-comments',
    tags: ['ai-saas', '办公', '协作'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.feishu.cn',
    scenarioTags: ['办公提效', '企业协作'],
  },
  {
    id: 'tool-saas-trae',
    name: 'Trae',
    desc: '字节跳动 AI IDE，适合 Agent 式编程',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 48000,
    icon: 'fa-code',
    tags: ['ai-saas', '编码'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.trae.ai',
    scenarioTags: ['编码助手'],
  },
  {
    id: 'tool-saas-wanxiang',
    name: '通义万相',
    desc: '阿里通义万相 AI 生图，适合中文提示词创作',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 61000,
    icon: 'fa-image',
    tags: ['ai-saas', '生图'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://tongyi.aliyun.com/wanxiang',
    scenarioTags: ['图像创作'],
  },
  {
    id: 'tool-saas-flux',
    name: 'Flux',
    desc: 'Black Forest Labs Flux 高质量文生图',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 52000,
    icon: 'fa-image',
    tags: ['ai-saas', '生图'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://blackforestlabs.ai',
    scenarioTags: ['图像创作'],
  },
  {
    id: 'tool-saas-capcut',
    name: '剪映 / CapCut',
    desc: '字节剪映 AI 剪辑与成片，适合短视频物料',
    category: 'platform',
    author: '业界精选',
    published: true,
    invokes: 95000,
    icon: 'fa-film',
    tags: ['ai-saas', '生视频'],
    sourceType: 'external',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://www.capcut.com',
    scenarioTags: ['视频创作'],
  },

  // —— 华为内部 AI 工具（发现页 · 马上能用 · 内部）——
  {
    id: 'tool-hw-assistant',
    name: '员工助手',
    desc: '华为内部办公助手，支持问答、流程指引与知识检索',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 186000,
    icon: 'fa-user-tie',
    tags: ['hw-internal', '对话'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl:
      'https://his.huawei.com/csop/index.html#/ToolInfo?samType=his&toolId=1706591788617216002',
    logoUrl: internalToolAssetUrl('employee-assistant.png'),
    scenarioTags: ['办公提效', '通用对话'],
  },
  {
    id: 'tool-hw-xiaowei',
    name: '小微助手',
    desc: '华为内部智能助理，支持日常问答与办公协同',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 152000,
    icon: 'fa-comments',
    tags: ['hw-internal', '对话'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl:
      'https://his.huawei.com/csop/index.html#/ToolInfo?samType=his&toolId=1706591788617216002',
    logoUrl: internalToolAssetUrl('employee-assistant.png'),
    scenarioTags: ['通用对话', '办公提效'],
  },
  {
    id: 'tool-hw-w3-qa',
    name: 'W3智能搜索',
    desc: 'W3 门户智能搜索，检索制度、流程与内部知识',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 128000,
    icon: 'fa-magnifying-glass',
    tags: ['hw-internal', '搜索', '对话'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://ai.huawei.com/w3Copilot/index.html#/home?lang=zh',
    logoUrl: internalToolAssetUrl('w3-search.png'),
    scenarioTags: ['办公提效', '知识'],
  },
  {
    id: 'tool-hw-cloudnote',
    name: '云笔记',
    desc: 'WeLink 云笔记与知识沉淀，支持协同编辑与智能摘要',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 98000,
    icon: 'fa-note-sticky',
    tags: ['hw-internal', '办公', '笔记'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://wenote.huawei.com/wenoteapp',
    logoUrl: internalToolAssetUrl('cloud-note.png'),
    scenarioTags: ['办公提效', '知识'],
  },
  {
    id: 'tool-hw-meeting',
    name: '会议AI听',
    desc: '会议实时转写与纪要生成，支持多语种与行动项提取',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 92000,
    icon: 'fa-headphones',
    tags: ['hw-internal', '办公', '会议'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl: 'https://wenote.huawei.com/wenoteapp',
    logoUrl: internalToolAssetUrl('cloud-note.png'),
    scenarioTags: ['办公提效'],
  },
  {
    id: 'tool-hw-xiaoluban',
    name: '小鲁班',
    desc: '研发效能小助手，支持排障、脚本与常用工具编排',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 76000,
    icon: 'fa-screwdriver-wrench',
    tags: ['hw-internal', '编码', '效能'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl:
      'https://openx.huawei.com/%E5%B0%8F%E9%B2%81%E7%8F%ADwelink%E6%9C%BA%E5%99%A8%E4%BA%BA/overview',
    logoUrl: internalToolAssetUrl('xiaoluban.jpg'),
    scenarioTags: ['编码助手', '办公提效'],
  },
  {
    id: 'tool-hw-digital-line',
    name: '企业数字产线',
    desc: '企业数字化产线助手，支撑流程编排、作业协同与效能看板',
    category: 'platform',
    author: '华为内部',
    published: true,
    invokes: 54000,
    icon: 'fa-industry',
    tags: ['hw-internal', '编码', '效能'],
    sourceType: 'internal',
    visibility: 'public',
    ownerDeptIds: [],
    ownerRegionId: null,
    homepageUrl:
      'https://his.huawei.com/csop/index.html#/ToolInfo?samType=his&toolId=1706591788617216002',
    logoUrl: internalToolAssetUrl('employee-assistant.png'),
    scenarioTags: ['办公提效', '平台'],
  },
];

/** 外部 SaaS 以 CSV catalog 为准；仅保留公司内部工具种子 */
export const PROTOTYPE_TOOLS: PrototypeToolSeed[] = [
  ...CORE_PROTOTYPE_TOOLS.filter((t) => !t.tags?.includes('ai-saas')),
  ...buildExternalToolSeedsFromCatalog(),
];

export function pruneRetiredDemoTools(
  tools: PrototypeToolSeed[],
): PrototypeToolSeed[] {
  const retired = new Set<string>(RETIRED_DEMO_TOOL_IDS);
  return tools.filter((t) => !retired.has(t.id));
}
